spring:
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true