spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 1234
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.r2dbc: DEBUG