# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres_db
    environment: 
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: postgres
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
