version: "3.5"

services:
  postgres:
    container_name: postgres
    image: postgres:13.2
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todolist
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/db
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Monta el script de inicialización

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/data/pgadmin

volumes:
  postgres_data:
  pgadmin_data:

