spring:
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/ecommerce
    database: "ecommerce"
    username: "postgres"
    password: "1234"

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.r2dbc: DEBUG